print("Hello Woeld!")
print("Hello Akash")
print("I am good")
print("How are you?")
print(47)
print(True)
print(False)
print(3.14)
print("I am learning Python", 47, True, 3.14)
print("I am learning Python", 47, True, 3.14, sep=" | ")
print("I am learning Python\n", 47, True, 3.14, sep=" | ")
